export enum MEMORY_CACHE_KEY {
  GITHUB_PROFILE = "GITHUB_PROFILE",
  GITHUB_CONTRIBUTIONS = "GITHUB_CONTRIBUTIONS",
  DISCORD_USER = "DISCORD_USER",
}

export const timeMilliseconds = {
  FIVE_MINUTES: 1000 * 60 * 5,
};

export const GITHUB_USERNAME = "EdvinTr";
